/*
 * Copyright 2026 1o1 Co. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Internal WebAuthn verification helpers (spec §2.5).
 *
 * These are thin wrappers around `@simplewebauthn/server` that:
 *   1. Map SimpleWebAuthn's thrown errors to a typed `reason` discriminant
 *      so callers never need to parse error strings.
 *   2. Reshape the registration material to drop fields that belong to the
 *      endpoint layer (userId, createdAt, nickname).
 *   3. Enforce the §2.4 sign-count corner case: when both stored counter and
 *      new counter are 0 (authenticators that always report 0), skip the
 *      strict-increase check — SimpleWebAuthn natively skips its throw for
 *      this case, so the post-verification guard handles the remaining check.
 *
 * NOT exported from the package barrel — internal use only.
 *
 * Error-reason regex mapping (re-validated against SimpleWebAuthn v13.3.3 source;
 * all four target strings are unchanged since v13.1.1):
 *   /origin/i   → "origin_mismatch"
 *   /challenge/i → "challenge_mismatch"
 *   /rp.?id/i   → "rp_id_mismatch"  (matches "RP ID" from UnexpectedRPIDHash)
 *   /counter/i  → "sign_count_regression"
 *
 * Deliberately unmapped: attestation certificate-chain failures. Since v13.3.2
 * (GHSA-6hxq-p678-4hr2) these throw "x5c could not be chained to any specified
 * trust anchor", wrapped per format as "... (Apple)" / "(Android Key)" / etc.
 * No regex above matches it, so it lands on "unknown" — the same bucket it fell
 * into before the bump, when the message read "Subject issuer did not match
 * issuer subject". Giving it its own discriminant is a behaviour change that
 * belongs in its own PR, not in an advisory bump.
 *
 * Cross-refs: Plan T25 / spec §2.5 / §2.4 sign-count
 */

import type { AuthenticatorTransport, WebAuthnCredential } from "@o3co/auth-provider-core";
import type { AuthenticationResponseJSON, RegistrationResponseJSON } from "@simplewebauthn/server";
import { verifyAuthenticationResponse, verifyRegistrationResponse } from "@simplewebauthn/server";

// ---------------------------------------------------------------------------
// Attestation (registration)
// ---------------------------------------------------------------------------

export interface AttestationVerificationInput {
	readonly response: RegistrationResponseJSON;
	readonly expectedChallenge: string;
	readonly expectedRpId: string;
	readonly expectedOrigins: readonly string[];
	/**
	 * WebAuthn UserVerificationRequirement (W3C §5.8.6).
	 *
	 * When "required": passes `requireUserVerification: true` to SimpleWebAuthn —
	 * the server enforces that the UV flag is set in the authenticator assertion.
	 * When "preferred" or "discouraged": passes `requireUserVerification: false` —
	 * UV is requested as a hint in the options (the hint is generated by the
	 * options endpoint), but the server does not reject assertions where UV is absent.
	 *
	 * Defaults to "preferred" when absent (same semantic as "preferred": no enforcement).
	 *
	 * NOTE: UV is a cryptographic property of the assertion (proof the user
	 * authenticated), not a policy decision. SimpleWebAuthn is the natural
	 * enforcement point. Plan T25 "policy decides UV" was a design-gap framing.
	 *
	 * Cross-refs: Codex Round 2 P1-1 / spec §2.5
	 */
	readonly userVerification?: "required" | "preferred" | "discouraged";
}

export type AttestationVerificationResult =
	| {
			readonly ok: true;
			readonly material: {
				readonly credentialId: string;
				/**
				 * COSE public key. `Uint8Array<ArrayBuffer>` rather than a bare
				 * `Uint8Array`: the value is always freshly allocated by
				 * `new Uint8Array(...)` below, so its backing store is a plain
				 * ArrayBuffer and never a SharedArrayBuffer. Stating that in the
				 * type keeps it assignable to `@simplewebauthn/server` >= 13.3.2's
				 * byte inputs without a second copy downstream.
				 */
				readonly publicKey: Uint8Array<ArrayBuffer>;
				readonly signCount: number;
				readonly transports?: ReadonlyArray<AuthenticatorTransport>;
				readonly backedUp: boolean;
			};
	  }
	| {
			readonly ok: false;
			readonly reason:
				| "origin_mismatch"
				| "challenge_mismatch"
				| "attestation_invalid"
				| "rp_id_mismatch"
				| "unknown";
	  };

export async function verifyWebAuthnAttestation(
	input: AttestationVerificationInput,
): Promise<AttestationVerificationResult> {
	try {
		const verification = await verifyRegistrationResponse({
			response: input.response,
			expectedChallenge: input.expectedChallenge,
			expectedOrigin: [...input.expectedOrigins], // S7: multi-origin support
			expectedRPID: input.expectedRpId,
			// Enforce UV when configured as "required"; otherwise false (hint only).
			// "preferred" and "discouraged" are request hints only — not server-enforced.
			// Cross-refs: Codex Round 2 P1-1 / spec §2.5
			requireUserVerification: (input.userVerification ?? "preferred") === "required",
		});

		if (!verification.verified || !verification.registrationInfo) {
			return { ok: false, reason: "attestation_invalid" };
		}

		const info = verification.registrationInfo;
		return {
			ok: true,
			material: {
				credentialId: info.credential.id,
				publicKey: new Uint8Array(info.credential.publicKey),
				signCount: info.credential.counter,
				// SimpleWebAuthn's AuthenticatorTransportFuture is a superset of our
				// AuthenticatorTransport (adds "cable" and "smart-card"). Cast to
				// unknown first to avoid the direct-super-type assignment error.
				transports: info.credential.transports as unknown as
					| ReadonlyArray<AuthenticatorTransport>
					| undefined,
				backedUp: info.credentialBackedUp,
			},
		};
	} catch (err) {
		return mapRegistrationError(err);
	}
}

function mapRegistrationError(err: unknown): AttestationVerificationResult {
	if (err instanceof Error) {
		if (/origin/i.test(err.message)) return { ok: false, reason: "origin_mismatch" };
		if (/challenge/i.test(err.message)) return { ok: false, reason: "challenge_mismatch" };
		if (/rp.?id/i.test(err.message)) return { ok: false, reason: "rp_id_mismatch" };
	}
	return { ok: false, reason: "unknown" };
}

// ---------------------------------------------------------------------------
// Assertion (authentication)
// ---------------------------------------------------------------------------

export interface AssertionVerificationInput {
	readonly credential: WebAuthnCredential;
	readonly response: AuthenticationResponseJSON;
	readonly expectedChallenge: string;
	readonly expectedRpId: string;
	readonly expectedOrigins: readonly string[];
	/**
	 * WebAuthn UserVerificationRequirement (W3C §5.8.6).
	 *
	 * Same semantics as AttestationVerificationInput.userVerification.
	 * Defaults to "preferred" when absent.
	 *
	 * Cross-refs: Codex Round 2 P1-1 / spec §2.5
	 */
	readonly userVerification?: "required" | "preferred" | "discouraged";
}

export type AssertionVerificationResult =
	| { readonly ok: true; readonly newSignCount: number }
	| {
			readonly ok: false;
			readonly reason:
				| "origin_mismatch"
				| "challenge_mismatch"
				| "rp_id_mismatch"
				| "signature_invalid"
				| "sign_count_regression"
				| "unknown";
	  };

export async function verifyWebAuthnAssertion(
	input: AssertionVerificationInput,
): Promise<AssertionVerificationResult> {
	try {
		const verification = await verifyAuthenticationResponse({
			response: input.response,
			expectedChallenge: input.expectedChallenge,
			expectedOrigin: [...input.expectedOrigins], // S7: multi-origin support
			expectedRPID: input.expectedRpId,
			credential: {
				id: input.credential.credentialId,
				// Defensive copy, for two independent reasons.
				//
				// 1. Type. `WebAuthnCredential.publicKey` is a bare `Uint8Array`
				//    (= `Uint8Array<ArrayBufferLike>`) on purpose: a store adapter's
				//    natural source is its driver's `Buffer`, which types as
				//    `Buffer<ArrayBufferLike>` and would not satisfy the narrower
				//    form. `@simplewebauthn/server` >= 13.3.2 requires
				//    `Uint8Array<ArrayBuffer>`. `new Uint8Array(view)` always
				//    allocates a fresh plain ArrayBuffer, so this CONVERTS rather
				//    than asserts — it stays correct even for the (legal, if
				//    exotic) adapter that hands back a SharedArrayBuffer-backed
				//    view, which no cast could make safe.
				// 2. Aliasing. The store contract documents these bytes as logically
				//    immutable, and the in-process adapter returns its own stored
				//    array by reference. Copying keeps a third-party library from
				//    holding a live alias of the store's internal state.
				//
				// Cost is one ~77-byte COSE-key copy per assertion.
				publicKey: new Uint8Array(input.credential.publicKey),
				counter: input.credential.signCount,
				// Cast: SimpleWebAuthn expects AuthenticatorTransportFuture[]
				// (superset of our AuthenticatorTransport — adds "cable" and
				// "smart-card"). Our stored values are a strict subset; the cast
				// is safe since the common values round-trip without loss.
				// biome-ignore lint/suspicious/noExplicitAny: transport superset cast — see comment
				transports: input.credential.transports as any,
			},
			// Enforce UV when configured as "required"; otherwise false (hint only).
			// Cross-refs: Codex Round 2 P1-1 / spec §2.5
			requireUserVerification: (input.userVerification ?? "preferred") === "required",
		});

		if (!verification.verified) {
			return { ok: false, reason: "signature_invalid" };
		}

		const newCounter = verification.authenticationInfo.newCounter;
		const stored = input.credential.signCount;

		// §2.4 sign-count corner case: if both stored AND new counters are 0,
		// allow (some authenticators always report 0).
		// SimpleWebAuthn already skips its own counter throw for the 0/0 case
		// (condition: (counter > 0 || credential.counter > 0) && counter <= credential.counter).
		// We still guard here so the return type is explicit.
		if (newCounter === 0 && stored === 0) {
			return { ok: true, newSignCount: 0 };
		}

		// For all other cases: SimpleWebAuthn already throws a counter error
		// when newCounter <= stored (and at least one is > 0), so this guard
		// only fires in edge cases where SimpleWebAuthn returns verified=true
		// but the counter did not increase (should not happen in practice).
		if (newCounter <= stored) {
			return { ok: false, reason: "sign_count_regression" };
		}

		return { ok: true, newSignCount: newCounter };
	} catch (err) {
		return mapAuthenticationError(err);
	}
}

function mapAuthenticationError(err: unknown): AssertionVerificationResult {
	if (err instanceof Error) {
		if (/origin/i.test(err.message)) return { ok: false, reason: "origin_mismatch" };
		if (/challenge/i.test(err.message)) return { ok: false, reason: "challenge_mismatch" };
		if (/rp.?id/i.test(err.message)) return { ok: false, reason: "rp_id_mismatch" };
		if (/counter/i.test(err.message)) return { ok: false, reason: "sign_count_regression" };
	}
	return { ok: false, reason: "unknown" };
}
